import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getAuth, signOut, onAuthStateChanged } from "firebase/auth";
import { useRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import { getFirestore, collection, getDocs } from "firebase/firestore";
import firebase from '../database/index'
import withAuth from '../middleware/WithAuth';
import { GlobalContext } from '../contexts/GlobalContext';
const Blog: NextPage = () => {
  const router = useRouter()
  const [blog, setBlog] = useState<any>([])
  const { data, setData } = useContext(GlobalContext)

  const [openPopup, setOpenPopup] = useState<boolean>(false)
  const db = getFirestore(firebase)
  const getDb = async () => {
    try {
      const citiesCol = collection(db, "blog");
      const citySnapshot = await getDocs(citiesCol);
      const cityList = citySnapshot.docs.map(doc => doc.data());
      setData(cityList)
    } catch (error) {
      console.log(error)
    }
  }
  const handleOpenPopup=(data: any)=>{
    setOpenPopup(true)
    setBlog(data)
  }
  useEffect(() => {
    getDb()
  }, [])
  const handleLogout = () => {
    const auth = getAuth();
    signOut(auth).then(() => {
      router.push("login")
    }).catch((error) => {
      // An error happened.
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog
        </h1>
        <div onClick={handleLogout}>Logout</div>

        <div className={styles.grid}>
          {data.length > 0 && data.map((blog: any, index: number) => (
            <div className={styles.card} key={index} onClick={()=>handleOpenPopup(blog)}>
              <h2>{blog.title}</h2>
              <p>{blog.decription}</p>
              <img src={blog.image} alt="" style={{ width: 200, height: 200 }} />
            </div>
          ))}
        </div>
      </main>
      {
        openPopup &&
        <div className={styles.popup}>
          <div>
            <div className={styles.inside}>
              <div className={styles.close} onClick={()=>setOpenPopup(false)}>x</div>
              <h1>{blog.title}</h1>
              <img src={blog.image} alt="" style={{ width: 200, height: 200 }} />
              <p>{blog.content}</p>
            </div>
            <div className={styles.outside} onClick={()=>setOpenPopup(false)}></div>
          </div>

        </div>
      }

    </div>
  )
}

export default withAuth(Blog);
