import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getAuth, signOut, onAuthStateChanged } from "firebase/auth";
import { useRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import { getFirestore, collection, getDocs } from "firebase/firestore";
import firebase from '../database/index'
import withAuth from '../middleware/WithAuth';
import { GlobalContext } from '../contexts/GlobalContext';
const Home: NextPage = () => {
  const router = useRouter()
  const { setUser } = useContext(GlobalContext)

  const handleLogout = () => {
    const auth = getAuth();
    signOut(auth).then(() => {
      router.push("login")
      setUser(null)
    }).catch((error) => {
      // An error happened.
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home page
        </h1>
        <div onClick={handleLogout} style={{ cursor: "pointer" }}>Logout</div>
        <div onClick={() => router.push('blog')} style={{ marginTop: 10, cursor: "pointer" }}>
          Go to blog page
        </div>
      </main>

    </div>
  )
}

export default withAuth(Home);
